### ISSUE TITLE
你这个只能拖动一次吗？

### ISSUE THREAD

**Issue by zidanpiaoguo** [wuyr/RandomDragLayout#1]
我改了一下你的代码，但是我发现你写的每次都移除view ，重新在加入，可不可以，点击移动，然后在次移动，也可以继续移动呢

**Comment by zidanpiaoguo** [comment]
你当时是因为什么原因，没有移动本身的view，而是隐藏view，重新绘画view呢

**Comment by wuyr** [comment]
调用这个方法： reset() // 重置状态 (重新初始化)

**Comment by wuyr** [comment]
至于为什么没有直接移动子View，这个在博客中有说明的：
4.至于子View的旋转与移动，如果是直接通过setRotation、setTranslation、layout、offsetTopAndBottom等一系列方法直接改变View属性的话，考虑到视图层级关系，可能会出现被其他View遮挡的现象，还有，随着手指不断地移动，很大几率会移动超出了View自身的边界，导致内容显示不全。
链接：https://blog.csdn.net/u011387817/article/details/84136291

**Comment by macy7** [comment]
一句 卧槽 表达了我内心的卧槽
